export enum EventTypes {
    LOGOUT = 'LOGOUT',
    ADDRESS_UPDATE = 'ADDRESS_UPDATE',
    SHOW_FAVORITE_PRODUCT = 'SHOW_FAVORITE_PRODUCT',
    SHOW_PRODUCT_CATEGORY = 'SHOW_PRODUCT_CATEGORY',
    SHOW_ORDER_HISTORY = 'SHOW_ORDER_HISTORY',
    SHOW_PRODUCT = 'SHOW_PRODUCT',
    LOGGED_IN = 'LOGGED_IN',
    NEW_ORDER_PLACED = 'NEW_ORDER_PLACED',
    PRODUCT_UPDATE = 'PRODUCT_UPDATE',
    STORE_REVIEW = 'STORE_REVIEW',
    VOICE_SEARCH_DONE = 'VOICE_SEARCH_DONE',
}
